name: Build and Test

on:
  push:
    branches: [main, dockerr]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build image & push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/2tbofsmth/lb2:latest

  test:
    name: Pull image & run tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/2tbofsmth/lb2:latest

      - name: Run container and execute tests
        run: docker run ghcr.io/2tbofsmth/lb2:latest pytest

